MiniShop.Mvc/Controllers/UnitController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MiniShop.Dto;
using MiniShop.Mvc.Code;
using MiniShop.Mvc.HttpApis;
using MiniShop.Mvc.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace MiniShop.Mvc.Controllers
{
    public class UnitController : BaseController
    {
        private readonly IUnitApi _unitApi;
        public UnitController(ILogger<UnitController> logger, IMapper mapper, IUserInfo userInfo,
            IUnitApi unitApi) : base(logger, mapper, userInfo)
        {
            _unitApi = unitApi;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var maxCodeResult = await _unitApi.GetMaxCodeByShopId(_userInfo.ShopId);
            if (!maxCodeResult.Success)
            {
                return Json(new Result() { Success = maxCodeResult.Success, Status = maxCodeResult.Status, Msg = maxCodeResult.Msg });
            }
            int maxCode = maxCodeResult.Data == 0 ? 100 : maxCodeResult.Data;
            if (maxCode == 999)
            {
                return Json(new Result() { Success = false, Msg = "该商店拥有的单位数量已达上限", Status = (int)HttpStatusCode.BadRequest });
            }
            UnitCreateDto model = new UnitCreateDto
            {
                ShopId = _userInfo.ShopId,
                Code = maxCode,
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddAsync(UnitCreateDto model)
        {
            var result = await ExecuteApiResultModelAsync(() => { return _unitApi.AddAsync(model); });
            return Json(new Result() { Success = result.Success, Msg = result.Msg, Status = result.Status });
        }

        public async Task<IActionResult> UpdateAsync(int id)
        {
            var result = await ExecuteApiResultModelAsync(() => { return _unitApi.GetByIdAsync(id); });
            if (result.Success)
            {
                return View(result.Data);
            }
            return Json(new Result() { Success = result.Success, Msg = result.Msg, Status = result.Status });
        }
      
        [HttpPost]
        public async Task<IActionResult> UpdateAsync(UnitDto model)
        {
            var dto = _mapper.Map<UnitUpdateDto>(model);
            var result = await ExecuteApiResultModelAsync(() => { return _unitApi.UpdateAsync(dto); });
            return Json(new Result() { Success = result.Success, Msg = result.Msg, Status = result.Status });
        }

        [ResponseCache(Duration = 0)]
        [HttpGet]
        public async Task<IActionResult> GetPageOnShopAsync(int page, int limit)
        {
            var result = await ExecuteApiResultModelAsync(() => { return _unitApi.GetPageOnShopAsync(page, limit, _userInfo.ShopId); });
            if (!result.Success)
            {
                return Json(new Result() { Success = result.Success, Status = result.Status, Msg = result.Msg });
            }
            return Json(new Table() { Data = result.Data.Item, Count = result == null ? 0 : result.Data.Total });
        }

        [ResponseCache(Duration = 0)]
        [HttpGet]
        public async Task<IActionResult> GetPageOnShopWhereQueryCodeOrNameAsync(int page, int limit, string code, string name)
        {
            code = System.Web.HttpUtility.UrlEncode(code);
            name = System.Web.HttpUtility.UrlEncode(name);
            var result = await ExecuteApiResultModelAsync(() => { return _unitApi.GetPageOnShopWhereQueryCodeOrName(page, limit, _userInfo.ShopId, code, name); });
            if (!result.Success)
            {
                return Json(new Result() { Success = result.Success, Status = result.Status, Msg = result.Msg });
            }
            return Json(new Table() { Data = result.Data.Item, Count = result == null ? 0 : result.Data.Total });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var result = await ExecuteApiResultModelAsync(() => { return _unitApi.DeleteAsync(id); });
            return Json(new Result() { Success = result.Success, Msg = result.Msg, Status = result.Status });
        }

        [HttpDelete]
        public async Task<IActionResult> BatchDeleteAsync(string ids)
        {
            List<string> idsStrList = ids.Split(",").ToList();
            List<int> idsIntList = new List<int>();
            foreach (var id in idsStrList)
            {
                idsIntList.Add(int.Parse(id));
            }

            if (idsIntList.Count > 0)
            {
                var result = await ExecuteApiResultModelAsync(() => { return _unitApi.BatchDeleteAsync(idsIntList); });
                return Json(new Result() { Success = result.Success, Msg = result.Msg, Status = result.Status });
            }
            else
            {
                return Json(new Result() { Success = false, Msg = "查找不到要删除的单位", Status = (int)HttpStatusCode.NotFound });
            }

        }
    }
}

MiniShop.Mvc/Views/Unit/Add.cshtml
@model UnitCreateDto

<!DOCTYPE html>
<html lang="en"  xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/component/pear/css/pear.css" />
</head>

<body>
    <form class="layui-form" asp-controller="Unit" asp-action="Add" data-ajax="true" data-ajax-method="post" data-ajax-success="onSuccess">
        <div class="mainBox">
            <div class="main-container">
                <input type="hidden" asp-for="ShopId"/>
                <div class="layui-form-item">
                    <label class="layui-form-label" style="width: 20%">编码</label>
                    <div class="layui-input-block">
                        <input type="text" name="Code" value="@Model.Code" readonly="readonly" lay-verify="" autocomplete="off" placeholder="" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label" style="width: 20%">名称</label>
                    <div class="layui-input-block">
                        <input type="text" name="Name" value="@Model.Name" lay-verify="" autocomplete="off" placeholder="请输入类别名称" class="layui-input">
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom">
            <div class="button-container">
                <button type="submit" class="pear-btn pear-btn-primary pear-btn-sm" lay-submit="" lay-filter="">
                    <i class="layui-icon layui-icon-ok"></i>
                    提交
                </button>
                <button type="reset" class="pear-btn pear-btn-sm">
                    <i class="layui-icon layui-icon-refresh"></i>
                    重置
                </button>
            </div>
        </div>
    </form>

    <script src="~/component/layui/layui.js"></script>
    <script src="~/component/pear/pear.js"></script>
    <script src="~/js/verify.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>

    <script>
        layui.use(['form', 'jquery'], function () {
            let form = layui.form;
            let $ = layui.jquery;

            form.verify({
                nameCheck: function (value) {
                    if (!str_2_32_len(value))
                        return '请输入正确的类别名称！2到32位！'
                },
            });
        });

        var onSuccess = function (result) {
            if (result.success) 
            {
                layer.msg(result.msg, { icon: 1, time: 1000 }, function () {
                    parent.layer.close(parent.layer.getFrameIndex(window.name));
                    parent.layui.table.reload("unit-table",{
                        url: 'GetPageOnShop',
                    });
                });
            } 
            else
            {
                parent.layer.open({
                    type: 2,
                    title: '',
                    shade: 0.1,
                    area: ['900px', '600px'],
                    content: '/Error/Error?statusCode=' + result.status + '&errorMsg=' + result.msg,
                });
            }
        };
    </script>

</body>
</html>

MiniShop.Mvc/Views/Unit/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>单位管理</title>
    <link rel="stylesheet" href="~/component/pear/css/pear.css" />
</head>
<body class="pear-container">
    <div class="layui-card">
        <div class="layui-card-body">
            <form class="layui-form" action="">
                <div class="layui-form-item">
                    <div class="layui-form-item layui-inline">
                        <label class="layui-form-label">单位编码</label>
                        <div class="layui-input-inline">
                            <input type="text" name="code" placeholder="" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-form-item layui-inline">
                        <label class="layui-form-label">单位名称</label>
                        <div class="layui-input-inline">
                            <input type="text" name="name" placeholder="" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-form-item layui-inline">
                        <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="unit-query">
                            <i class="layui-icon layui-icon-search"></i>
                            查询
                        </button>
                        <button type="reset" class="pear-btn pear-btn-md">
                            <i class="layui-icon layui-icon-refresh"></i>
                            重置
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="layui-card">
        <div class="layui-card-body">
            <table id="unit-table" lay-filter="unit-table"></table>
        </div>
    </div>

    <script type="text/html" id="unit-toolbar">
        <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">
            <i class="layui-icon layui-icon-add-1"></i>
            新增
        </button>
        <button class="pear-btn pear-btn-danger pear-btn-md" lay-event="batchRemove">
            <i class="layui-icon layui-icon-delete"></i>
            删除
        </button>
    </script>

    <script type="text/html" id="unit-bar">
        <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit"><i class="layui-icon layui-icon-edit"></i></button>
        <button class="pear-btn pear-btn-danger pear-btn-sm" lay-event="remove"><i class="layui-icon layui-icon-delete"></i></button>
    </script>

    <script type="text/html" id="unit-createTime">
        {{layui.util.toDateString(d.createdTime, 'yyyy-MM-dd')}}
    </script>

    <script src="~/component/layui/layui.js"></script>
    <script src="~/component/pear/pear.js"></script>
    <script>
            layui.use(['table', 'form', 'jquery', 'common'], function () {
                let table = layui.table;
                let form = layui.form;
                let $ = layui.jquery;
                let common = layui.common;

                let cols = [
                    [{
                        type: 'checkbox'
                    },
                    {
                        title: 'ID',
                        field: 'id',
                        align: 'center',
                        width: 100
                    },
                    {
                        title: '编码',
                        field: 'code',
                        align: 'center',
                    },
                    {
                        title: '名称',
                        field: 'name',
                        align: 'center'
                    },
                    {
                        title: '创建日期',
                        field: 'createdTime',
                        align: 'center',
                        templet: '#unit-createTime'
                    },
                    {
                        title: '操作',
                        toolbar: '#unit-bar',
                        align: 'center',
                        width: 130
                    }
                    ]
                ]

                table.render({
                    elem: '#unit-table',
                    url: 'GetPageOnShop',
                    page: true,//开启分页
                    cols: cols,
                    skin: 'line',
                    toolbar: '#unit-toolbar',
                    defaultToolbar: [{
                        title: '刷新',
                        layEvent: 'refresh',
                        icon: 'layui-icon-refresh',
                    }, 'filter', 'print', 'exports']
                });

                table.on('tool(unit-table)', function (obj) {
                    if (obj.event === 'remove') {
                        window.remove(obj);
                    } else if (obj.event === 'edit') {
                        window.edit(obj);
                    }
                });

                table.on('toolbar(unit-table)', function (obj) {
                    if (obj.event === 'add') {
                        window.add();
                    } else if (obj.event === 'refresh') {
                        window.refresh();
                    } else if (obj.event === 'batchRemove') {
                        window.batchRemove(obj);
                    }
                });

                form.on('submit(unit-query)', function (data) {
                    table.reload('unit-table', {
                        url: 'GetPageOnShopWhereQueryCodeOrName',
                        page: {
                            curr:1,//重新从第一页开始
                        },
                        where: data.field
                    })
                    return false;
                });


                window.add = function () {
                    layer.open({
                        type: 2,
                        title: '新增',
                        shade: 0.1,
                        area: [common.isModile() ? '100%' : '500px', common.isModile() ? '100%' : '500px'],
                        content: '/unit/add',
                    });
                }

                window.edit = function (obj) {
                    layer.open({
                        type: 2,
                        title: '修改',
                        shade: 0.1,
                        area: [common.isModile() ? '100%' : '500px', common.isModile() ? '100%' : '400px'],
                        content: '/unit/update/' + obj.data['id'],
                    });
                }

                window.remove = function (obj) {
                    layer.confirm('确定要删除该用户', {
                        icon: 3,
                        title: '提示'
                    }, function (index) {
                        layer.close(index);
                        let loading = layer.load();
                        $.ajax({
                            url: "/unit/delete/" + obj.data['id'],
                            dataType: 'json',
                            type: 'delete',
                            success: function (result) {
                                layer.close(loading);
                                if (result.success) {
                                    layer.msg(result.msg, {
                                        icon: 1,
                                        time: 1000
                                    }, function () {
                                        //obj.del();
                                        table.reload('unit-table');
                                    });
                                } else {
                                    parent.layer.open({
                                        type: 2,
                                        title: '',
                                        shade: 0.1,
                                        area: ['900px', '600px'],
                                        content: '/Error/Error?statusCode=' + result.status + '&errorMsg=' + result.msg,
                                    });
                                }
                            }
                        })
                    });
                }

                window.batchRemove = function (obj) {

                    var checkIds = common.checkField(obj, 'id');

                    if (checkIds === "") {
                        layer.msg("未选中数据", {
                            icon: 3,
                            time: 1000
                        });
                        return false;
                    }

                    layer.confirm('确定要删除这些用户', {
                        icon: 3,
                        title: '提示'
                    }, function (index) {
                        layer.close(index);
                        let loading = layer.load();
                        $.ajax({
                            url: "/unit/batchDelete?ids=" + checkIds,
                            dataType: 'json',
                            type: 'delete',
                            success: function (result) {
                                layer.close(loading);
                                if (result.success) {
                                    layer.msg(result.msg, {
                                        icon: 1,
                                        time: 1000
                                    }, function () {
                                            table.reload('unit-table');
                                    });
                                } else {
                                    parent.layer.open({
                                        type: 2,
                                        title: '',
                                        shade: 0.1,
                                        area: ['900px', '600px'],
                                        content: '/Error/Error?statusCode=' + result.status + '&errorMsg=' + result.msg,
                                    });
                                }
                            }
                        })
                    });
                }

                window.refresh = function (param) {
                    table.reload('unit-table',{
                        url: 'GetPageOnShop'
                    });
                }
            })
    </script>
</body>
</html>